/* ------------------------------------------------------------------ */
/*      item            : {{ name }}.hxx
        generated by    : {{ maker }}
        date            : {{ date }}
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : {{ codegenversion }}
        language        : C++{{ headercomments }}
*/

#ifndef {{ name }}_hxx
#define {{ name }}_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
};
#endif

#if !defined(__DCO_STANDALONE)
#include <gencodegen.h>
#if GENCODEGEN != {{ codegenversion }}
#error "Generated {{ name }}.hxx too old, please clean with 'make mrproper'"
#endif
#include <dueca/CommObjectTraits.hxx>
#endif

#include <iostream>
{{ extraheader }}
{{ typeincludes }}{{ plug_header_include }}

{{ namespacecmd0 }}
{{ enumdec }}
{{ namespacecmd1 }}{{ extrainclude }}

{{ publicfunctionsdec }}

#if !defined(__DCO_STANDALONE)
namespace dueca {
{{ enumtraits }}
};
#endif
{{ plug_header_code }}

#endif